[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.0"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 