[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.0"
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--no-audit --no-fund"
  CI = "false"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 